# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'TSOfflineGeocoder-Example' do
	pod "TSOfflineGeocoder", :path => "../../"
end

target 'TSOfflineGeocoder-ExampleTests' do
	pod "TSOfflineGeocoder", :path => "../../"
end

